### ISSUE TITLE
Portal Client Permission added "view_service_marketplace"

### ISSUE THREAD

**Issue by jjeroch** [tractusx-team-portal-onboarding/devenv#129]
To do:

- Create the permission inside the client mentioned in the ticket title
- Assigned the permission to ALL composite roles inside the client

**Comment by ntruchsess** [comment]
view_service_marketplace created and added to the following composite roles:
CX Admin
CX User
Business Admin
Developer
IT Admin

**Comment by ntruchsess** [comment]
implemented in #131
