### ISSUE TITLE
technical_roles_management client - add "DAPS Certificate"

### ISSUE THREAD

**Issue by jjeroch** [tractusx-team-portal-onboarding/devenv#146]
Type: Composite Role
Associated Role: 
<img width="787" alt="image" src="https://user-images.githubusercontent.com/94133633/194133291-583cb0ca-4dee-42f2-ba00-150b916ef291.png">

**Comment by ntruchsess** [comment]
done

**Comment by ntruchsess** [comment]
https://github.com/tractusx-team-portal-onboarding/devenv/pull/163
