### ISSUE TITLE
technical_roles_management client - add "Dataspace Discovery"

### ISSUE THREAD

**Issue by jjeroch** [tractusx-team-portal-onboarding/devenv#149]
Type: Composite Role
<img width="824" alt="image" src="https://user-images.githubusercontent.com/94133633/194825894-e06a5e08-aafc-4230-852c-4736cbb17d4c.png">

**Comment by ntruchsess** [comment]
done

**Comment by ntruchsess** [comment]
https://github.com/tractusx-team-portal-onboarding/devenv/pull/163
