### ISSUE TITLE
technical_roles_management client - add "Service Management"

### ISSUE THREAD

**Issue by jjeroch** [tractusx-team-portal-onboarding/devenv#153]
This is a composite role.
Please add following permissions of the Portal Client to this new composite role:
<img width="778" alt="image" src="https://user-images.githubusercontent.com/94133633/195522387-486ca387-9494-40fd-8688-6429922163cc.png">

**Comment by ntruchsess** [comment]
done

**Comment by ntruchsess** [comment]
implemented in https://github.com/tractusx-team-portal-onboarding/devenv/pull/163
