### ISSUE TITLE
Portal Client - Create "Service Manager" with assigned permissions (see ticket)

### ISSUE THREAD

**Issue by jjeroch** [tractusx-team-portal-onboarding/devenv#165]
<img width="508" alt="image" src="https://user-images.githubusercontent.com/94133633/197989707-01679bcc-032b-40ab-8e74-d5a2b0317c81.png">
<img width="438" alt="image" src="https://user-images.githubusercontent.com/94133633/197989777-7b050eed-bb6a-470c-b3f7-f62ea79bf142.png">
<img width="450" alt="image" src="https://user-images.githubusercontent.com/94133633/197989810-047587d8-60dd-4012-bddd-b9a893778bed.png">
<img width="403" alt="image" src="https://user-images.githubusercontent.com/94133633/197989835-9f2152dd-4782-4873-9dea-3c570e3dc3a4.png">

**Comment by ntruchsess** [comment]
implemented in https://github.com/tractusx-team-portal-onboarding/devenv/pull/166
