### ISSUE TITLE
Portal Client Permission added "activate_subscription"

### ISSUE THREAD

**Issue by jjeroch** [tractusx-team-portal-onboarding/devenv#64]

**Comment by ntruchsess** [comment]
implemented in https://github.com/tractusx-team-portal-onboarding/devenv/pull/79
shall this be part of a composite-role?

**Comment by jjeroch** [comment]
@ntruchsess  please map the permission to the role "CX Admin" for now. Later we will off course assign it to another role. But to have an easy dev handling, I would like to keep this with the CX Admin

**Comment by ntruchsess** [comment]
done: https://github.com/tractusx-team-portal-onboarding/devenv/pull/79/commits/7cb0943639bf6355d8b09c2e14b718cde3878970
