### ISSUE TITLE
Portal Client Permission added "add_connectors"

### ISSUE THREAD

**Issue by jjeroch** [tractusx-team-portal-onboarding/devenv#71]

**Comment by jjeroch** [comment]
@ntruchsess please map the permission to the role "CX Admin" for now. Later we will off course assign it to another role. But to have an easy dev handling, I would like to keep this with the CX Admin

**Comment by ntruchsess** [comment]
done: https://github.com/tractusx-team-portal-onboarding/devenv/commit/631c323319a78a833bdbe8aadbded9a7584a10ec
