### ISSUE TITLE
Create New Client - "technical_roles_management"

### ISSUE THREAD

**Issue by jjeroch** [tractusx-team-portal-onboarding/devenv#82]
**Client:** technical_roles_management
**Type:** bearer

**Roles:**
#1 Digital Twin Management
    Composite Role: yes
    Associated Permissions: all assigned under the Client "Cl4-CX-DigitalTwin"
#2 Semantic Model Management
    Composite Role: yes
    Associated Permissions: all assigned under the Client "Cl3-CX-Semantic"
#3 Wallet Management
    Composite Role: yes
    Associated Permissions: update_wallet and view_wallet under the Client "Cl5-CX-Custodian"

**Comment by ntruchsess** [comment]
implemented
